swagger: "2.0"
info:
  title: 致简生活 API
  description: 致简生活是一款微信小工具，您可以通过这个查看天气和快递等生活服务
  version: 1.0.0
  termsOfService: https://tolife.yuhanle.com
  contact:
    email: shiboven@foxmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
schemes:
- http
- ' https'
paths:
  /express/ebusinessOrderHandle:
    post:
      tags:
      - express
      description: 查询快递订单和状态
      operationId: ExpressController.EbusinessOrderHandle
      parameters:
      - in: query
        name: RequestData
        description: The RequestData for query
        required: true
        type: string
      - in: query
        name: RequestType
        description: The RequestType for query
        required: true
        type: string
      responses:
        "200":
          description: '{string} success'
        "401":
          description: wei chaxun dao danhao
  /toilet/around:
    post:
      tags:
      - toilet
      description: 查询位置附近的厕所
      operationId: ToiletController.SearchToilet
      parameters:
      - in: query
        name: location
        description: The location for query
        required: true
        type: string
      responses:
        "999":
          description: error
        "1000":
          description: '{string} query success'
  /user/info:
    post:
      tags:
      - user
      description: 获取用户信息
      operationId: UserController.GetUserInfo
      parameters:
      - in: query
        name: token
        description: token
        required: true
        type: string
      - in: query
        name: userid
        description: userid
        required: true
        type: string
      responses:
        "00":
          description: info success
  /user/login:
    post:
      tags:
      - user
      description: 登录系统
      operationId: UserController.Login
      parameters:
      - in: query
        name: username
        description: username
        required: true
        type: string
      - in: query
        name: password
        description: password
        required: true
        type: string
      - in: query
        name: weinfo
        description: weinfo
        required: true
        schema:
          $ref: '#/definitions/.interface{}'
      responses:
        "00":
          description: login success
        "01":
          description: user not exist
  /user/update:
    post:
      tags:
      - user
      description: 登录系统
      operationId: UserController.Update
      parameters:
      - in: query
        name: token
        description: token
        required: true
        type: string
      responses:
        "00":
          description: update success
  /weather/weatherInfo:
    get:
      tags:
      - weather
      description: 查询实时天气和天气预报
      operationId: WeatherController.SearchWeather
      parameters:
      - in: query
        name: city
        description: The city for query
        required: true
        type: string
      responses:
        "200":
          description: '{string} login success'
        "403":
          description: user not exist
definitions:
  .interface{}:
    type: object
tags:
- name: weather
  description: |
    Operations about object
- name: express
  description: |
    Operations about object
- name: toilet
  description: |
    Operations about object
- name: user
  description: |
    Operations about object
